#!/usr/bin/with-contenv bash

[[ ! -d /config/organizr/.git ]] && (git clone https://github.com/causefx/Organizr /config/organizr/)

# Create Config file (else fail2ban will not launch)
if [ ! -e "/config/organizr/loginLog.json" ] ; then
    touch "/config/organizr/loginLog.json"
fi

# Update GeoIP
mkdir -p /usr/share/GeoIP
cd /usr/share/GeoIP
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz || { echo 'Could not download GeoLiteCountry, exiting.' ; exit 1; }
gunzip -f GeoIP.dat.gz
